use std::{
    fmt, fs::{self, File}, io::{Error, Write}, net::{
        IpAddr,
        SocketAddr,
    }
};
use regex::Regex;

use crate::error::{
    fatal_error,
    error,
};

pub struct Config {
    address: IpAddr,
    port: u16,
}

pub trait FromFile {
    fn from_file(path: &str) -> Result<Config, FileNotFoundError>;

    fn get_setting_value(split_file: &str, search_term: &str, error_on_missing: bool) -> Result<Option<String>, RequiredSettingMissingError>;
}

impl FromFile for Config {
    fn from_file(path: &str) -> Result<Config, FileNotFoundError> {
        let file_string: String = match fs::read_to_string(path) {
            Ok(f) => f,
            Err(e) => {
                error::<Error>("Unable to load config file", &e);

                return Err(FileNotFoundError)
            }
        };

        println!("{:?}", Config::get_setting_value(&file_string, "Address", false));

        ////println!("{:?}", file_string);
        todo!()
    }

    fn get_setting_value(split_file: &str, search_term: &str, error_on_missing: bool) -> Result<Option<String>, RequiredSettingMissingError> {
        let regex: Regex = Regex::new(&(r"(?ms)(".to_owned() + search_term + "=.*)\n")).expect("This \
        should remain a valid RegEx, as it has been tested");
        // This RegEx matches for the search, all values after the term before a new line, and only
        // matches if the match begins on a new line, reducing the risk of matching from a comment

        ////println!("{}", regex);
        
        let captures: regex::Captures<'_> = match regex.captures(split_file) {
            Some(cap) => cap,
            None => {
                if error_on_missing {
                    return Err(RequiredSettingMissingError);
                } else {
                    return Ok(None);
                };
            },
        };

        println!("{:?}", captures);

        todo!()
    }
}

pub trait NewFile {
    fn new_file(path: &str) -> Result<(), FileExistsError>;
}

impl NewFile for Config {
    fn new_file(path: &str) -> Result<(), FileExistsError> {
        let file_exists: bool = match fs::exists(&path) {
            Ok(r) => r,
            Err(e) => {
                error::<std::io::Error>("unable to check if config file exists", &e);
                true
            },
        };

        if file_exists {
            return Err(FileExistsError)
        };

        // This also checks for a file existing, the overlap is not an operational concern
        let mut file: File = match File::create_new(&path) {
            Ok(f) => f,
            Err(e) => {
                error::<Error>("File creation error", &e);
                return Err(FileExistsError)
            },
        };

        // Standard config for example purposes
        let standard_config: &str = "\
        # Default config, generated by Astra. This \
        configuration file must be edited to be used \
        normally.\n\
        Address=127.0.0.1\n\
        Port=80,443";

        match file.write(standard_config.as_bytes()) {
            Ok(_) => (),
            Err(e) => {
                fatal_error::<std::io::Error>("Unable to write new config file", &e);
            }
        }

        return Ok(())
    }
}

pub trait GetBindSocket {
    fn get_bind_socket(&self) -> SocketAddr;
}

impl GetBindSocket for Config {
    fn get_bind_socket(&self) -> SocketAddr {
        return (self.address, self.port).into()
    }
}

#[derive(Debug, Clone)]
pub struct FileExistsError;

impl fmt::Display for FileExistsError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "file with the provided path already exists")
    }
}

impl std::error::Error for FileExistsError {}

#[derive(Debug, Clone)]
pub struct FileNotFoundError;

impl fmt::Display for FileNotFoundError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "file with the provided path does not exist")
    }
}

impl std::error::Error for FileNotFoundError {}

#[derive(Debug, Clone)]
pub struct RequiredSettingMissingError;

impl fmt::Display for RequiredSettingMissingError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "config file is missing at least one required setting")
    }
}

impl std::error::Error for RequiredSettingMissingError {}